name: verify

on:
  pull_request:

jobs:
  bash:
    name: Lint bash scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: bash -n contrib/*

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container:
      image: quay.io/openshift-virtualization/wasp-agent-builder:2409261312-0878b7f

    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: make test-ci
